//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Departamentoes = new HashSet<Departamento>();
        }
    
        public long ID { get; set; }
        public string Nome { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public long RoleID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public bool IsAdmin { get; set; }
        public long EmpresaID { get; set; }
        public string NrFuncionario { get; set; }
        public decimal CustoHora { get; set; }
        public long DepartamentoID { get; set; }
        public decimal Compensacoes { get; set; }
        public int NrDiasFerias { get; set; }
        public bool Activo { get; set; }
        public string NrFardamento { get; set; }
        public string Sapato { get; set; }
        public string Calça { get; set; }
        public string Polo { get; set; }
        public string Casaco { get; set; }
        public string Bata { get; set; }
        public Nullable<System.DateTime> DataAdmissao { get; set; }
        public string Morada { get; set; }
        public string Telefone { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DataNascimento { get; set; }
        public string CC { get; set; }
        public Nullable<System.DateTime> ValidadeCC { get; set; }
        public string NIF { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Departamento> Departamentoes { get; set; }
        public virtual Departamento Departamento { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual Role Role { get; set; }
    }
}
